route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-notifications'
receivers:
  - name: 'email-notifications'
    email_configs:
      - to: [EMAIL_ADDRESS]
        from: [EMAIL_ADDRESS]
        smarthost: 'smtp.gmail.com:587'
        auth_username: [EMAIL_ADDRESS]
        auth_password: '[PASSWORD]'
